import { CheckinsData, StandardsData } from './types'
import { scoreDay, scoreTodayLive, rollingAvg } from './score'

export interface MotivationContext {
  score: number          // today 0-10
  trend: 'up' | 'down' | 'flat' | 'new'
  todayPct: number       // 0-1
  missedCategories: string[]
  topStreak: number
  dayOfWeek: number      // 0=Sun 6=Sat
  perfectDaysThisWeek: number
  rolling7: number | null
}

// ── Message pools ────────────────────────────────────────────────────────────

const PERFECT = [
  "You got everything done today. That's what it looks like when you're serious about it.",
  "Full day. Every single one. This version of you is the one that wins.",
  "Perfect score. Do it again tomorrow and don't overthink it.",
  "Everything checked off. The person you want to become showed up today.",
  "Nothing missed. That's the standard. Keep it.",
  "100% today. Most people won't. You did.",
  "All done. This is what discipline looks like when it's actually working.",
  "Every single one. Remember how this feels on the hard days.",
  "You didn't negotiate with yourself today. That's the whole difference.",
  "Full marks. Keep this as your reference point when things get tough.",
  "100% means you respected every promise you made to yourself today.",
  "Every box checked. The compounding has already started.",
  "You showed up completely today. That's rarer than you think.",
  "All promises kept. This is your identity now, guard it.",
  "The scoreboard says 10. Your future self is grateful.",
  "You set the promises and you lived them. Full circle.",
  "Nothing left undone. That's integrity made visible.",
  "Perfect day. The version of you that wins consistently looks exactly like this.",
  "Every promise honored. The gap between vision and reality just closed a little more.",
  "All done. You built today exactly the way you meant to.",
  "10 out of 10. Stack these and watch everything change.",
  "You finished everything. Most people don't even start everything.",
  "All in today. No half measures. This is what a real commitment looks like.",
  "100%. Own it and repeat it.",
  "Perfect execution. The discipline muscle got stronger today.",
  "Every promise kept. That's the foundation everything else is built on.",
  "You delivered on every commitment you made to yourself today.",
  "Full day, full effort, full score. What else is there?",
  "Not one promise left behind. This is who you're becoming.",
  "Today you were exactly who you said you'd be.",
  "Perfect. File this feeling away for the hard days.",
  "All done. You earned the right to rest tonight.",
  "100% complete. This is not an accident, it's character.",
  "All promises checked. This is what full alignment feels like.",
  "Perfect score. The momentum is real, don't waste it tomorrow.",
  "Every promise met. You've made this version of yourself non-negotiable.",
  "Nothing left on the table. That's how you close a day.",
  "You were relentless today. That's what a perfect day looks like.",
  "Every box ticked. Your future self will thank this version of you.",
  "Complete. The person you're building is taking shape and you can feel it.",
  "All done and nothing skipped. You should feel good about that.",
  "100% means you took yourself seriously today. Keep doing that.",
  "Everything done. Simple as that. Now do it again.",
  "You showed up for yourself completely today. Not everyone does.",
  "Perfect day. Now the only goal is making tomorrow just as good.",
  "All promises met. This is what a real commitment looks like.",
  "Full score. The person you want to be and the person you are got a little closer today.",
  "Everything checked. Go rest well, you earned it.",
  "100% today. This is who you are when you decide to be.",
  "All done. Perfect. Now protect this as your new normal.",
]

const ZERO = [
  "Nothing today. The gap between who you are and who you want to be just got a little wider.",
  "Zero done. Tomorrow you either close that gap or accept it.",
  "A zero day is a choice. Make a different one tomorrow.",
  "Nothing done today. Not a bad day but a skipped one, and there's a difference.",
  "The version of you that does nothing will always lose to the version that does something.",
  "Zero. That's a full day of potential just sitting there unused.",
  "You had the same 24 hours as everyone else. You chose zero.",
  "Nothing checked. Your future self is watching this moment.",
  "A zero day isn't neutral, it's a step backward.",
  "Every promise you made to yourself, you ignored today. That says something about priorities.",
  "Nothing. Not one. That's not a rough day, that's a decision.",
  "You made these promises for a reason. Today you walked past all of them.",
  "Zero is the only score that guarantees nothing changes.",
  "Nothing done today. The version of you that wins doesn't have many of these.",
  "0 out of 10. You know what to do tomorrow.",
  "A completely skipped day. Not once, not halfway, zero.",
  "Nothing completed. Your future self is watching this one.",
  "Zero today. It doesn't define you unless it becomes a pattern.",
  "Nothing. That's not rest. That's avoidance.",
  "You made these promises because they matter. Today you acted like they don't.",
  "Zero is the easiest score to get and the hardest to justify.",
  "A day of zero moves you backward, not forward.",
  "Nothing done. Every tomorrow deserves better than a repeat of this.",
  "Zero. Not okay, not acceptable, not who you want to be.",
  "The promises exist. Today they were completely invisible to you.",
  "Zero today. The comeback starts the moment you decide this is the last one.",
  "Nothing. Not because you couldn't. Because you didn't.",
  "A full day and not one promise honored. That's a pattern worth breaking immediately.",
  "Zero today. Make tomorrow the day that stops this.",
  "Nothing completed. Show up tomorrow with everything you didn't give today.",
  "Zero. This day happened. Make sure tomorrow happens differently.",
  "Not one. You know what that means. Start fresh, tonight if you can.",
  "Zero. The hardest day to recover from is the one where you didn't even try.",
  "Nothing. Every promise skipped today is a small debt to your future self.",
  "0 today. The only thing worse than a zero is pretending it doesn't matter.",
  "Completely blank today. Don't carry this into tomorrow.",
  "Zero. Your promises don't care about your excuses and neither does your future.",
  "Nothing done. This is the low point. The only way now is up.",
  "Zero. One day can be the pivot. Make tomorrow that day.",
  "Nothing today. It's okay to have a rough one but don't make it two in a row.",
  "Zero. You know why. Deal with the why and show up tomorrow.",
  "Nothing checked today. That's fine. Tomorrow you check something.",
  "Zero. You deserved better from yourself today. Give it tomorrow.",
  "Nothing done. Tomorrow is a clean page. Fill it.",
  "Zero today. It happens. Just don't let it happen again tomorrow.",
  "Nothing. You're capable of more than this and you know it.",
  "Zero. The reset starts now, not tomorrow morning.",
  "Nothing today. The gap doesn't close itself, but you can start closing it tomorrow.",
  "Zero. That's the score. Tomorrow you change it.",
  "Nothing done today. Tomorrow you do something. Anything. Start there.",
]

const ARE_YOU_KIDDING = [
  "This score is embarrassing you and you know it. Fix it.",
  "Below 2.5. Your promises aren't promises if you don't actually live them.",
  "The gap between who you want to be and what you're doing right now is massive. Start closing it.",
  "You made these promises yourself. If not now then when?",
  "This is the version of you that looks back with regret. You can still choose differently.",
  "Brutal truth: today you failed your own promises. Tomorrow is a fresh count.",
  "Under 2.5. You're capable of far more than this.",
  "Barely anything done. This isn't who you decided to be.",
  "A score this low is a signal that something is off. Address it.",
  "Almost nothing today. The minimum wasn't even close to met.",
  "You made these promises for a reason. Today you treated them like they don't exist.",
  "Sub 2.5. Your future self is getting further away, not closer.",
  "This is the rock bottom score range. Stop visiting here.",
  "Nothing about today reflects the promises you made to yourself.",
  "Under 2.5 is not a rough patch, it's a choice. Break it.",
  "You're barely showing up for yourself. That has to change.",
  "This score says one thing: you're not taking this seriously yet.",
  "Almost zero effort today. The person you want to be demands more.",
  "Embarrassingly low and you know it. That discomfort is useful, use it.",
  "Under 2.5 means almost everything was skipped. That's not a bad day, that's a pattern.",
  "Your promises are a contract with yourself. Today you defaulted on that.",
  "The lowest tier. You've been here before. You know it leads nowhere good.",
  "This score doesn't reflect your ability. It reflects your current choices. Change them.",
  "Almost nothing done. The gap between your life and the one you want is measured in scores like this.",
  "Below 2.5 is the zone where nothing builds, nothing compounds, nothing changes.",
  "You're running on fumes and calling it a day. It's not. Start over now.",
  "This is the score of someone who gave up before they started. That's not you, act like it.",
  "Under 2.5 is not acceptable to the person you said you'd become.",
  "Barely anything completed. This is the day that makes or breaks momentum.",
  "A score this low means today was mostly wasted. Don't add tomorrow to that list.",
  "You've made higher promises than this score shows. Go back and honor them.",
  "This is the version of you that you've been trying to leave behind.",
  "Almost nothing. Every skipped promise is a vote against the life you want.",
  "This low a score means you're not fighting for your own promises. Start fighting.",
  "Under 2.5. The gap is growing. Close it before it feels permanent.",
  "Minimal effort today. Your future self doesn't forgive these days easily.",
  "This score hurts to look at. Good. Let it motivate you.",
  "Below 2.5. The compound interest of this score is a life you don't want.",
  "You nearly skipped everything. That's not rest, that's retreat.",
  "Almost zero. Not zero, you can still salvage something today.",
  "This score says you haven't fully committed yet. Commitment changes today.",
  "Under 2.5 is where potential goes to disappear. Don't stay here.",
  "Nearly everything skipped. Your promises are waiting for you to come back.",
  "This isn't a setback, this is you not showing up. There's a difference.",
  "Below 2.5. One decision right now could turn this day around.",
  "You've done better. You know better. Do better.",
  "This score won't build the life you want. Not even close.",
  "Sub 2.5 and you know it. The honest thing now is to keep one promise. Then another.",
  "Almost nothing done. The person you want to be would not let this stand.",
  "Under 2.5. Brutal, honest, and completely correctable. Correct it.",
]

const POOR = [
  "Under 5. You're capable of more than this and you know it.",
  "More missed than kept today. Flip that ratio tomorrow.",
  "Halfway isn't your standard. You can do more.",
  "Poor day. Not a poor person. Get back on track.",
  "You made these promises. Right now you're under them. Climb.",
  "Some done, not enough. Tomorrow start with the first promise before anything else.",
  "Under 5. The second half of your promises are still waiting.",
  "More skipped than completed. The math doesn't lie.",
  "You started but didn't finish. Finish tomorrow.",
  "Below halfway. The momentum you need starts with one more kept promise.",
  "Under 5. This is not the pace that gets you where you want to go.",
  "More gaps than wins today. The trend needs to reverse.",
  "You crossed some off but not enough. The bar was set by you, meet it.",
  "Poor score, not permanent. Correctable starting right now.",
  "Under half today. Make sure tomorrow starts strong.",
  "You did something. That's the only thing keeping this from being a zero. Do more tomorrow.",
  "Below 5 means more than half your promises were ignored. That's significant.",
  "Not enough today. You know which ones you skipped. Get them tomorrow.",
  "Under 5. The foundation you're trying to build doesn't hold at this rate.",
  "Some done, too many missed. Come back tomorrow with more urgency.",
  "Below half is below where you want to be. You already know this.",
  "Under 5 and not the direction you want to go.",
  "More missed than kept. The pattern needs to break here.",
  "You gave partial effort today. Partial effort gets partial results.",
  "Under 5. The life you want requires more than half your promises kept.",
  "Too many skipped. The ones you missed didn't disappear, they're waiting.",
  "Below halfway. The resistance won more rounds than you today. Win more tomorrow.",
  "Under 5 is where good intentions live without action to back them up.",
  "More than half skipped. Today is a reminder, not a verdict.",
  "Poor day. Own it, fix it, don't repeat it.",
  "Under 5 means the majority of your promises went unkept. That's the work to do.",
  "Not your best, not close, not acceptable if this becomes your average.",
  "Below halfway, and the tipping point is close. Push past it tomorrow.",
  "Too many empty checkboxes. Fill them in.",
  "Under 5. Not failure, a signal. The signal says more.",
  "You did some of the work. The rest still needs doing.",
  "Poor score. The only response is a better one tomorrow.",
  "Below 5. The difference between this score and a good one is focus.",
  "Under half. Your promises don't negotiate and neither should you.",
  "More not done than done. Tomorrow reverse that.",
  "Under 5 is the zone where habits stall and drift begins. Step out of it.",
  "Below halfway. One by one, the skipped ones need to become kept ones.",
  "Too many gaps today. Gaps compound into distance from your goals.",
  "Under 5. Not who you're becoming, just a reminder of who you don't want to stay.",
  "Poor day. It stings because you know you can do better.",
  "Below halfway. The momentum is there, it just needs more of you.",
  "Under 5. This is fixable. Start fixing.",
  "More missed than kept. Tomorrow is a clean slate, use it fully.",
  "Poor score. It stings because you know you can do better.",
  "Under 5. Climb. The version of you above the line is waiting.",
]

const BAD = [
  "Decent but not great. You know the difference.",
  "Past halfway. Finish what you started tomorrow.",
  "Good effort but not your best. You've had better days, build back to them.",
  "Above average isn't your goal. Excellence is. Close the gap.",
  "Progress but not enough. Push the last few promises harder.",
  "Above 5 but not above 7.5. The gap is closeable.",
  "More done than missed today. That's the positive. Not enough is the negative.",
  "You're in the middle range. You know where to push.",
  "Solid start. The finish is where it counts.",
  "Over halfway but under the bar. The bar is 7.5, keep climbing.",
  "5 to 7.4. You're doing the work but leaving some on the table.",
  "Most promises kept but not all. The unfinished ones are the ones that matter most.",
  "Good enough isn't your destination.",
  "Above average by most standards but below yours, and yours are what count.",
  "You did more than most people. You didn't do everything you could. There's a difference.",
  "The discipline to push through the last few is what separates you.",
  "Better than poor but not as good as you're capable of. Push it.",
  "Over halfway but the ceiling is higher than this.",
  "Some left undone. The undone ones are there for a reason, address that reason.",
  "5 to 7.4 is the zone where people get comfortable. Don't get comfortable.",
  "Above the midpoint but still below your best. Close the distance.",
  "Most done but not all. The almost there feeling should push you, not satisfy you.",
  "You're in range but not in form. Get in form.",
  "Good but not great. Not great is where the work is.",
  "Above 5, under 7.5. The gap to good is smaller than you think.",
  "Partial. Go keep the rest.",
  "Over halfway, under the mark. The last push is the hardest and the most important.",
  "You did most of the work. The remaining work is what builds character.",
  "Between 5 and 7.5, this is where resolve gets tested. Pass the test.",
  "The majority kept. The minority left is the difference between this score and a great one.",
  "Above average day but average isn't your goal.",
  "Good effort. The promises you skipped still matter. Get them.",
  "Solid but not complete. Solid is a stepping stone, not a destination.",
  "Above halfway and below the line. You know which side you want to be on.",
  "5 to 7.4, the progress zone. Don't mistake progress for arrival.",
  "Most promises kept. The remaining few are the ones you resist most. Go get them.",
  "You're doing the work but not all of it. Do all of it.",
  "Above 5 means you're trying. Under 7.5 means you're not trying hard enough yet.",
  "Good but not great is a comfortable place to stay if you let it be. Don't.",
  "Above the midpoint, below the mark. Close that gap tomorrow.",
  "Most of your promises most of the time is not the standard.",
  "Between 5 and 7.5. You've been above this before. Go back there.",
  "Good work but incomplete work. Finish it.",
  "Above average performance, below personal best. Which one matters to you?",
  "Over halfway is fine. Not all the way is not fine.",
  "5 to 7.4, the zone of the almost committed. Commit fully.",
  "More done than missed. Still room left. Fill it.",
  "You did enough to be proud of something but not enough to be proud of everything.",
  "Good day in the making. Make it all the way.",
  "Above 5, under 7.5. One zone left. Enter it.",
]

const GOOD = [
  "Strong day. This is your floor now, not your ceiling.",
  "Above 7.5. You're building something real here.",
  "High score. Keep the streak alive. Don't let tomorrow be the exception.",
  "Consistency is the only strategy that actually works. You're proving it.",
  "This is what a good day looks like. Stack them.",
  "Above 7.5, this is the range where real change happens.",
  "Strong performance. The compound interest starts here.",
  "You're in the zone. Stay there.",
  "High standard lived today. This is what alignment feels like.",
  "Almost everything done. Whatever you missed is tomorrow's first priority.",
  "7.5 or above. You're in the tier most people never reach consistently.",
  "Strong day. Make this your new normal.",
  "Above 7.5, the version of you that wins lives here.",
  "You're doing it. Not sometimes. Today. Keep doing it.",
  "Great performance. The goal is to make this feel automatic.",
  "Near the top of your range. Push for the top.",
  "Strong. This is what execution looks like.",
  "Above 7.5. You're in the discipline tier. Stay there.",
  "Good score. The only next step is a perfect one.",
  "Almost at 10. Whatever kept you from it, remove that friction tomorrow.",
  "Strong day. Your promises are becoming your identity.",
  "7.5 plus. This is the range that changes lives over time.",
  "You showed up well today. Show up the same way tomorrow.",
  "High performance. The promises you're keeping are becoming habits.",
  "Above 7.5, this is the zone where self trust is built.",
  "Strong, consistent, winning. Keep all three.",
  "Near complete day. The discipline required for this is significant.",
  "Good score means good choices. Repeat the choices.",
  "Above 7.5. The ceiling from here is 10. Go get it.",
  "Strong day. Not many people hit this consistently. You're one of them.",
  "High standard lived. This is what makes the difference a year from now.",
  "7.5 plus is rare. You're in the rare group. Stay there.",
  "Good day. Great is one push further. Make tomorrow great.",
  "Strong execution. The habits are forming. Don't break the chain.",
  "Above 7.5, the score that builds momentum worth keeping.",
  "You're doing the hard work consistently. That's the entire game.",
  "High score, low resistance. This is what it looks like when you're locked in.",
  "Good day. This is not the time to ease off, it's the time to push higher.",
  "Strong performance. The version of you that succeeds long term looks like this.",
  "Above 7.5, you're in the building phase. Keep building.",
  "Great score. The next question is: can you do this again tomorrow?",
  "Strong. The days that look like this are the ones that matter most.",
  "7.5 or above. You earned this. Earn it again.",
  "High execution today. The gap to 10 is small. Bridge it.",
  "Good performance. You're above the line. Stay above the line.",
  "Strong day. The discipline is working. Don't interrupt it.",
  "Above 7.5 means you're living your promises, not just making them.",
  "Good score. The next level is 10. You know what that looks like.",
  "Strong, consistent, this is the version of you that gets everything you've been working toward.",
  "Above 7.5. This is who you are when you show up fully. Show up fully every day.",
]

const IMPROVING = [
  "Trend is up. Momentum is real, don't waste it.",
  "You're improving. That's all that matters today.",
  "Score rising. The compound effect is starting to show.",
  "Each better day makes the next one easier. Keep stacking.",
  "Upward trajectory. Protect it.",
  "The arrow is pointing up. Follow it.",
  "Improving. The direction matters more than the current position.",
  "You're on the way up. Don't look down.",
  "Score is climbing. That's discipline in motion.",
  "Better than yesterday. Make tomorrow better than today.",
  "Rising trend. This is what a comeback looks like from the inside.",
  "You reversed the direction. That takes more strength than people realize.",
  "Improving day over day. This is the compounding phase, protect it.",
  "The trend is your friend right now. Don't betray it.",
  "Upward. The only direction worth travelling.",
  "You're building. Every improved day is a brick.",
  "Rising score is a rising version of yourself. Keep going.",
  "The trajectory is right. The speed will follow.",
  "Better than yesterday. That's the only benchmark that counts.",
  "You corrected course. Most people don't. You did.",
  "Improving trend, this is momentum. Momentum is fragile. Guard it.",
  "Score is going up. You're doing something right. Keep doing it.",
  "Upward movement. The discipline is working.",
  "Each day better than the last. This is how habits become permanent.",
  "Rising. The version of you at the top of this trend is worth fighting for.",
  "You're gaining altitude. Don't level off now.",
  "Improving. The gap between you and your best self is closing.",
  "The score went up. The effort went up with it. Connect those two facts.",
  "Better performance, better direction, better version of yourself emerging.",
  "Upward trend. This is the window where everything changes if you don't stop.",
  "Rising. The first few days of improvement are the most important. You're in them.",
  "Score climbing. Stay locked in.",
  "Improving. You broke the downward pattern. Now build the upward one.",
  "Each better day is proof you can do it. Collect more proof.",
  "The trend is rising. What you do next determines if it keeps rising.",
  "You're improving. That's the story. Keep writing it.",
  "Score is up. The discipline muscle is getting stronger.",
  "Rising trend. Don't treat this as the destination, treat it as the launchpad.",
  "Better today. Better tomorrow. That's the only plan you need.",
  "Improving. The momentum is yours. Use it.",
  "Score going up means you're choosing differently. Choose the same way tomorrow.",
  "Upward. The hardest part was reversing direction. You did it. Now accelerate.",
  "Better than before. The bar is rising with you.",
  "Rising score. The compound interest on this trend is everything you want.",
  "Improving. Every day you go up, the version you're becoming gets a little closer.",
  "You're on an upswing. Don't let anything interrupt it.",
  "Score trending up. This is what winning feels like in the middle of the process.",
  "Better. That's the word. Hold onto it. Keep earning it.",
  "The trend is clear: up. Match the trend with your effort.",
  "Improving. The arc of your progress is bending toward the person you intend to be.",
]

const DECLINING = [
  "Trend is down. Catch it before it becomes a pattern.",
  "Three steps forward, two steps back is still forward. Stop the slide here.",
  "Declining score. You've been here before. You know how to reverse it.",
  "The drift starts small. You're noticing it now, that's the first move.",
  "Don't let one bad week become your new normal.",
  "Downward trend. This is the moment to stop and reverse.",
  "Score dropping. The easiest time to fix this is right now.",
  "Declining. Not done, just declining. There's still time to turn it.",
  "The trend is down. The response is up.",
  "You've been here before. You came back before. Come back again.",
  "Sliding. Recognize it, reject it, reverse it.",
  "Downward. The slope is gentle now, it won't stay that way.",
  "Score is dropping. The cause is specific. Find it and remove it.",
  "Declining trend. This is where character shows up or checks out.",
  "The direction is wrong. Change the direction.",
  "Each lower day makes the next one easier to justify. Don't justify it.",
  "Dropping score. The momentum that built this can rebuild it.",
  "Declining. You know what you're skipping. Stop skipping it.",
  "The trend is down. You've felt this before. You know how to fight it.",
  "Sliding. Small slides become falls. Catch this one now.",
  "Downward trend. Not where you want to be and not where you have to stay.",
  "Score declining. The habits are loosening. Tighten them.",
  "You're drifting. Drift has a direction, straight toward who you don't want to be.",
  "The trend says down. You say otherwise. Prove it tomorrow.",
  "Declining. Patterns this early are the easiest to break. Break it.",
  "Score is dropping. Each day you let it drop costs you more than one day.",
  "Downward trend means something changed. Find what changed and change it back.",
  "Sliding. The window to stop this without a major recovery is now.",
  "Decline in progress. You've reversed worse. Reverse this.",
  "The score is dropping. The answer is always more promises kept, not fewer.",
  "Trending down but not crashing. Stop the trend.",
  "Declining. Every skipped promise is a contribution to a pattern you don't want.",
  "Score going down. The version of you that wins doesn't let this continue.",
  "The downward slide is correctable. Correct it before it becomes a habit.",
  "Dropping. You've built enough to know what recovery feels like. Go find it.",
  "Declining trend. This is the test. Pass it.",
  "Score is slipping. Grip it.",
  "Down trend. The longer it runs, the harder it is to reverse. Act now.",
  "Declining. The gap between your current score and your best is bigger today. Close it.",
  "Dropping. One strong day reverses the trend. Make tomorrow that day.",
  "The score is heading the wrong direction. Turn it around.",
  "Downward. Stop here. Not tomorrow, here.",
  "Sliding score. The habits that built your best days still exist. Go back to them.",
  "Declining. You're watching it happen. Stop watching and start doing.",
  "Trend is down. Every day you wait costs you momentum you'll have to rebuild.",
  "Dropping score. The time to catch this is before it feels impossible. Right now it's possible.",
  "Decline. Recognize it, own it, reverse it. In that order.",
  "Sliding down. You've climbed from here before. Start climbing.",
  "The trend is against you. Make tomorrow the day you go against the trend.",
  "Declining. The only thing worse than a bad trend is ignoring it.",
]

const MONDAY = [
  "Monday. The week is blank. Write something worth reading.",
  "New week. No excuses carried forward. Start clean.",
  "Monday is the most important day. What you do today sets the tone for all seven.",
  "Week starts now. Build early momentum.",
  "Monday is where the week is won or lost. Win it.",
  "New week, same promises. Keep them.",
  "Monday. The people who succeed start here with full effort.",
  "Seven days ahead. Today's score becomes the story of the week.",
  "Fresh week. Fresh resolve. Build on it.",
  "Monday sets the pattern. Set a good one.",
  "The week is yours to design. Design it well starting right now.",
  "First day of seven. Make it count.",
  "New week. This is the restart you've been waiting for, use it.",
  "Monday momentum is the most powerful kind. Build it.",
  "The week doesn't start on Wednesday. It starts today. Show up.",
  "Monday. Seven opportunities ahead. Treat this one as the most important.",
  "New week. Whatever last week looked like, today is a clean slate.",
  "Monday is either a drag or a launchpad. You decide which.",
  "Fresh start. The whole week is watching what you do today.",
  "New week, no carry over excuses, no carry over baggage. Only forward.",
  "Monday is the hardest day to be disciplined. That's exactly why it matters most.",
  "The week is a blank page. What you write today is the first line.",
  "Monday. Strong start equals strong week.",
  "New week means new opportunity to prove you're the person you said you'd be.",
  "Monday is the foundation. Build it right.",
  "Seven days. It starts with this one. Make this one mean something.",
  "Monday sets the tone. Make it a tone worth following for the next six days.",
  "Fresh week. No slipping into old patterns today.",
  "Monday. The easiest day to skip. The most important day not to.",
  "The week is wide open. Go into it with everything you have.",
  "Monday again. The chance to do this week better than last week. Take it.",
  "New week. The person who shows up fully today leads the week.",
  "Monday. Seven days to build something. Start building.",
  "The best weeks start with the best Mondays. Make this a good one.",
  "Monday, the day discipline compounds or dissolves for the rest of the week.",
  "New week. Bring your promises with you. Every single one.",
  "Monday. This is when you decide who shows up all week. Decide correctly.",
  "Seven fresh days ahead. Don't waste the first one.",
  "Monday momentum is real. Start it and carry it.",
  "New week, same mission, same promises. Get to work.",
  "Monday. The week is an investment. Today is the first deposit.",
  "Start strong, finish strong. Monday is where that starts.",
  "New week ahead. Make today the kind of day that makes the rest inevitable.",
  "Monday. The only way to have a great week is to have a great Monday.",
  "Fresh start. The whole week depends a little on what you do right now.",
  "Monday. Don't ease into the week. Step into it.",
  "New week. Make it better than last week. Start here.",
  "Monday. The week ahead is whatever you make it. Make it good.",
  "Seven days, starting now. What kind of week do you want to have?",
  "Monday. Show up. The rest follows.",
]

const FRIDAY = [
  "Friday. Did you earn the weekend?",
  "End of the week. How does the score look? Finish strong.",
  "Friday push. Don't let the week close without giving your best.",
  "What you do on Friday when no one is watching defines your discipline.",
  "Friday. The week ends with what you do today.",
  "Last day of the work week. Close it properly.",
  "Friday is where the week's story ends. Make it a good ending.",
  "Don't coast into the weekend. Sprint to it.",
  "Friday. Your future self doesn't care that it's Friday.",
  "End of the week. The promises don't know what day it is.",
  "Friday, the day discipline is most tested and most rewarded.",
  "Finish the week the way you started it: with full effort.",
  "Friday. The weekend you want is earned by the Friday you create.",
  "Close the week strong. Every promise kept today validates the whole week.",
  "Friday. How you finish is who you are.",
  "Last day of seven. Make it count for itself and for the week.",
  "Friday push. The momentum you build today carries into next week.",
  "Don't let Friday be the day the week unravels.",
  "Friday. Strong finish earns real rest.",
  "End the week on your terms.",
  "Friday, the day most people stop early. You stop when you're done.",
  "Close the week like you mean it.",
  "Friday. One more strong day and the week's story is a good one.",
  "The weekend is hours away. The promises are right now.",
  "Friday. Your discipline on this day says more than any other.",
  "End of week. Tally the score. Make the last number a good one.",
  "Friday. The discipline that matters most is the one nobody is watching.",
  "Finish strong. The difference between a great week and a mediocre one is often Friday.",
  "Friday. The week closes in hours. Make the close worth remembering.",
  "Don't mail it in on Friday. Friday is where real discipline shows.",
  "End of the week. Write a finish worth reading.",
  "Friday push. No coasting, no close enough, close fully.",
  "Friday. The week is watching how you end it.",
  "Last day. Full effort. That's the standard.",
  "Friday, the final test of a week's discipline. Pass it.",
  "Don't let the week end weakly. Friday is the crescendo.",
  "The weekend starts after this. Do this first.",
  "Friday. The version of you that succeeds long term doesn't have lazy Fridays.",
  "Close the gap between who you were on Monday and who you want to be on Sunday.",
  "Friday. Finish everything. Rest completely. In that order.",
  "Last day of the week. Make the last impression a strong one.",
  "Friday. The week's final score is being calculated. Push it up.",
  "Don't ease off on Friday. Ease off on Saturday after you've earned it.",
  "Friday. The promises don't take the day off. Neither do you.",
  "Close the week fully. Leave nothing undone that should be done.",
  "Friday. Strong weeks are built by people who show up completely on Fridays.",
  "End the week with the same urgency you started it with.",
  "Friday. The last chance to make this week's score something to be proud of.",
  "Don't waste the last day. It counts as much as the first.",
  "Friday. Close it out. Full promises. No exceptions.",
]

const WEEKEND = [
  "Weekend doesn't mean promises take a day off.",
  "Easy to drop promises on the weekend. That's exactly why you shouldn't.",
  "The disciplined person looks the same on Saturday as Monday.",
  "Rest and recover but don't abandon what you built this week.",
  "Weekend. The gap between you and your goals doesn't rest.",
  "Saturday or Sunday doesn't change who you're trying to become.",
  "The weekend is where discipline reveals itself or disappears.",
  "Rest is earned. Promises are kept regardless.",
  "Weekend. Most people drop off here. That's your competitive advantage.",
  "The promises exist on weekends too. That's what makes them promises.",
  "Two days where it's easy to slip. Don't slip.",
  "Weekend. Your future self doesn't get two days off.",
  "Saturday. Recover your energy. Don't recover your bad habits.",
  "The person you're becoming doesn't pause for weekends.",
  "Weekend is where habits either hold or break. Hold.",
  "Rest smart, recover well, but keep your promises intact.",
  "Saturday or Sunday, your commitment doesn't have a calendar.",
  "The weekend is the test. Weekday discipline is easy by comparison.",
  "Two days to either reinforce or undermine the week you just built.",
  "Weekend. The easiest time to slide. The worst time to let it happen.",
  "Rest and discipline aren't opposites. Both belong in your weekend.",
  "Saturday. The promises that survive the weekend are the ones that stick.",
  "Don't let the weekend undo the week.",
  "Your promises on a Saturday define your character more than any weekday.",
  "Weekend. Relax your schedule if you need to. Don't relax your promises.",
  "Two days. Keep the chain alive.",
  "The weekend is a test of how deep the habit goes. Show it goes all the way.",
  "Saturday or Sunday, the day doesn't excuse the choice.",
  "Rest is healthy. Abandonment is a habit. Know the difference.",
  "Weekend. Keep the streak. Keep the promises. Keep moving.",
  "The disciplined version of you doesn't have a weekend mode.",
  "Two days to prove the discipline is real. Use them.",
  "Saturday. The habits you keep on weekends are the habits that last.",
  "Weekend reset doesn't mean promise reset.",
  "The weekend is the reason weekday effort matters. Don't waste it.",
  "Rest up, recharge, but hold the line.",
  "Saturday. Some rest, all promises. That's the balance.",
  "Weekend. The gap between the person you are and who you want to be doesn't pause.",
  "Two days where excuses are loudest. Be louder.",
  "Weekend. Make the choices that weekday you will be proud of on Monday.",
  "The discipline that shows up on weekends is the discipline that changes lives.",
  "Saturday. Rest the body if needed. Don't rest the promises.",
  "Weekend. Show up the same way you showed up this week.",
  "Two days where most people slip. Be the one who doesn't.",
  "Weekend is not a reset, it's a continuation.",
  "The habit isn't real until it survives the weekend. Survive it.",
  "Saturday or Sunday, the promises are the promises.",
  "Rest well. Keep your promises. Do both.",
  "Weekend. Keep the fire going. It's harder to relight than to maintain.",
  "Two days. Your promises. Keep them.",
]

const STREAK = [
  (n: number) => `${n} day streak. You've built something real. Don't be the one who breaks it.`,
  (n: number) => `${n} days straight. That's not a habit anymore, that's identity.`,
  (n: number) => `${n} day run. Protect it.`,
  (n: number) => `${n} consecutive days. This is rare. Most people quit before here.`,
  (n: number) => `${n} days in a row. The chain is real. Don't break it.`,
  (n: number) => `${n} day streak. You've earned the right to call this a habit.`,
  (n: number) => `${n} straight days. Momentum this real is worth fighting for.`,
  (n: number) => `${n} days. You know what it cost to get here. Don't waste it.`,
  (n: number) => `${n} day run. The person who gets to ${n + 7} days is right in front of you.`,
  (n: number) => `${n} days in a row. This is what consistency looks like from the inside.`,
  (n: number) => `${n} day streak. You've outworked your past self ${n} times. Keep going.`,
  (n: number) => `${n} consecutive days. The compound interest on this is enormous.`,
  (n: number) => `${n} days straight. Breaking this now would cost more than continuing ever will.`,
  (n: number) => `${n} day run. Not an accident. Not luck. Repeated decisions.`,
  (n: number) => `${n} days. The habit is real. The results are coming.`,
  (n: number) => `${n} day streak. Most people never build anything this long.`,
  (n: number) => `${n} straight. The discipline required for this is significant. Honor it.`,
  (n: number) => `${n} days in a row. You've made yourself someone who does this. Keep being that person.`,
  (n: number) => `${n} day streak alive. The only task today is keeping it that way.`,
  (n: number) => `${n} days. You've earned something most people never will: a real streak.`,
  (n: number) => `${n} consecutive. This is the point where habits become character.`,
  (n: number) => `${n} day run. What started as effort is becoming automatic. Let it.`,
  (n: number) => `${n} days straight. You're not the same person who started this streak.`,
  (n: number) => `${n} day streak. The chain gets more valuable every single day.`,
  (n: number) => `${n} days in a row. Every day you continue, you make tomorrow easier.`,
  (n: number) => `${n} straight days. The version of you on day one would be impressed.`,
  (n: number) => `${n} day streak. This is the kind of consistency that changes everything.`,
  (n: number) => `${n} consecutive days. The longest journeys are made of single days just like this.`,
  (n: number) => `${n} day run. You've proven you can. Now prove you will keep going.`,
  (n: number) => `${n} days. Don't count the days, make the days count.`,
  (n: number) => `${n} day streak. The hardest part of a streak is always today. Do today.`,
  (n: number) => `${n} straight. The discipline is becoming effortless. That's the signal you've arrived.`,
  (n: number) => `${n} days in a row. Add one more.`,
  (n: number) => `${n} day streak. You've done this ${n} times. Do it once more.`,
  (n: number) => `${n} consecutive. The streak is proof that your promises are more than intentions.`,
  (n: number) => `${n} day run. Every day you didn't quit built this. Don't quit today.`,
  (n: number) => `${n} days straight. You're building a version of yourself that lasts.`,
  (n: number) => `${n} day streak. This is what showing up looks like, exactly like this.`,
  (n: number) => `${n} days. You've done the hardest thing: started and not stopped.`,
  (n: number) => `${n} consecutive days. The streak is alive. Keep it that way.`,
  (n: number) => `${n} day run. You're in the territory most people never explore.`,
  (n: number) => `${n} days in a row. The habit has roots now. Let it grow.`,
  (n: number) => `${n} day streak. Your discipline is compounding. So are the results.`,
  (n: number) => `${n} straight days. One more makes it ${n + 1}. That's today's only job.`,
  (n: number) => `${n} day run. The commitment you made ${n} days ago is paying off right now.`,
  (n: number) => `${n} consecutive days. This level of consistency is genuinely rare.`,
  (n: number) => `${n} days straight. The chain you've built is strong. Add another link.`,
  (n: number) => `${n} day streak. The version of you at ${n * 2} days is watching. Get there.`,
  (n: number) => `${n} days in a row. Every single one mattered. This one does too.`,
  (n: number) => `${n} day streak. You've become the kind of person who does this. Stay that person.`,
]

const MISSED_CATEGORIES: Record<string, string[]> = {
  Health: [
    "Health promises skipped. Your body is the only machine you can't replace.",
    "No health today. Everything else depends on this one.",
    "Your health promises exist because your body is the foundation of everything.",
    "Health missed. You can't perform at your best on a neglected machine.",
    "The health promises you skipped today will ask for payment eventually.",
    "No health checkins today. Your energy, focus, and mood all start here.",
    "Health skipped. The most important category got the least attention today.",
    "Your body keeps score even when you don't check in.",
    "Health promises missed. You can outwork anyone but you can't outwork your own neglect.",
    "No health today. The compounding effects of skipping this category are invisible until they're not.",
    "Health checkins skipped. The body you want is built in moments like the one you just passed.",
    "Missing health promises is borrowing against a loan that charges interest in years, not dollars.",
    "No health today. Every skipped health promise is a small vote against your vitality.",
    "Health missed. Your physical promises are non-negotiable, they just don't argue back.",
    "The health work skipped today gets added to tomorrow's balance.",
    "No health checkins. The strongest version of you is built on physical discipline.",
    "Health promises missed. The body follows the mind but the mind follows the body.",
    "Skipped health today. The investment with the highest return is the one you just passed on.",
    "No health work today. Your energy for everything else depends on this.",
    "Health missed. The most irreplaceable asset you have didn't get tended to today.",
    "Health promises skipped. Your body remembers every day you honored it and every day you didn't.",
    "No health today. Short term comfort, long term cost. Know the difference.",
    "Health missed. The gap between your physical best and your current state grows with each skip.",
    "Skipped your health promises. The machine needs maintenance, give it what it needs.",
    "No health checkins. What you do with your body today shapes what your body can do tomorrow.",
    "Health promises missed. Take care of the one body you have.",
    "No health today. Every skipped promise here has a physical cost that compounds silently.",
    "Health missed. Your performance in every other category is limited by this one.",
    "Skipped health. The version of you that lives your best life takes care of the basics first.",
    "No health today. Your body doesn't have a replacement plan, treat it accordingly.",
    "Health promises missed. These aren't optional, they're the prerequisites for everything else.",
    "No health checkins. The discipline of physical promises bleeds into every other area.",
    "Health skipped. Today's skipped promises are tomorrow's starting deficit.",
    "No health work today. The promises you made in this category are there for a reason.",
    "Health missed. The most powerful version of you starts with physical discipline.",
    "Skipped your health promises. The body is infrastructure, maintain it.",
    "No health today. The cost of neglect here is paid in quality of life.",
    "Health missed. Every day you honor these promises is a deposit in your future health.",
    "No health checkins. The body you're building, or not building, starts with today.",
    "Health promises skipped. Physical discipline creates mental discipline. You need both.",
    "No health today. Don't borrow from your future self, pay forward instead.",
    "Health missed. The promises in this category are the foundation everything else stands on.",
    "Skipped health. Your body is the vehicle for every goal you have. Maintain the vehicle.",
    "No health checkins today. These promises exist because you know how important they are.",
    "Health missed. Take the health promises seriously, your future self is counting on it.",
    "No health today. The investment you didn't make today is a withdrawal from tomorrow.",
    "Health promises missed. There is no area of your life that doesn't benefit from your health.",
    "Skipped health. The most important category got left behind today.",
    "No health today. Honor the body that carries you through every goal you've ever set.",
    "Health missed. These promises are a commitment to yourself. Keep it.",
  ],
  Relationship: [
    "Relationships need daily deposits. You missed today's.",
    "The people you love noticed even if they didn't say it.",
    "Relationship promises missed. Connection requires consistent investment.",
    "No relationship checkins today. The people who matter most deserve more than your leftover time.",
    "Relationship promises skipped. Love is a verb, not just a feeling.",
    "No relationship work today. The best investment you can make is in the people you care about.",
    "Relationship missed. People don't drift apart suddenly, they drift through small daily neglects.",
    "No relationship promises today. The quality of your relationships determines the quality of your life.",
    "Relationship checkins skipped. The people in your life are the reason the rest of it matters.",
    "Relationship missed. Every small act of connection compounds into a deep bond over time.",
    "No relationship work today. The most important people in your life deserve daily attention.",
    "Relationship promises skipped. Love grows in the everyday moments, you skipped today's.",
    "No relationship checkins. The people who matter most deserve to feel that they matter.",
    "Relationship missed. Strong relationships are built in small, consistent moments.",
    "No relationship today. The investment you didn't make in someone else's life today was a missed opportunity.",
    "Relationship promises missed. You can succeed everywhere else and fail here. Don't let that happen.",
    "No relationship work today. The people who love you deserve the best version of you.",
    "Relationship skipped. The connections you don't tend will eventually need repair.",
    "No relationship checkins. The health of your relationships is part of your overall promises.",
    "Relationship missed. Every day you invest in your relationships is a day the bond grows stronger.",
    "No relationship today. Your relationships don't maintain themselves, you maintain them.",
    "Relationship promises skipped. The people closest to you feel the presence or absence of your attention.",
    "No relationship work today. What you give to your relationships, you get back with interest.",
    "Relationship missed. The best version of your life includes strong, tended relationships.",
    "No relationship checkins. The world's highest achievers know that relationships are the ultimate measure.",
    "Relationship promises missed. Don't let the important people in your life become afterthoughts.",
    "No relationship today. The daily deposits into your relationships are what make them last.",
    "Relationship skipped. People feel valued through consistent attention, not occasional grand gestures.",
    "No relationship checkins. The relationships you take for granted are the ones most at risk.",
    "Relationship missed. Your promises in this category reflect how much you value your people.",
    "No relationship work today. The most important meeting of the day might have been with someone you love.",
    "Relationship promises skipped. The investment here pays dividends in belonging, support, and joy.",
    "No relationship today. Who you are in your relationships reflects who you truly are.",
    "Relationship missed. Don't let busyness be the reason the most important people feel forgotten.",
    "No relationship checkins. Relationships are built in the boring, beautiful, ordinary moments.",
    "Relationship promises missed. These promises exist because you know connection doesn't happen by accident.",
    "No relationship work today. The people who matter most deserve more than what's left over.",
    "Relationship skipped. The strongest people in the world are strong because of their relationships.",
    "No relationship today. The quality of your life will ultimately be measured by the quality of your connections.",
    "Relationship missed. Daily attention to the people you love is not a luxury, it's a necessity.",
    "No relationship checkins. The person you want to be shows up fully for the people they love.",
    "Relationship promises skipped. Invest in people before they have to ask you to.",
    "No relationship work today. The relationships that last are the ones that receive daily care.",
    "Relationship missed. Being present for the people in your life is one of the highest promises you can keep.",
    "No relationship today. The time you didn't give to someone who matters was time they noticed.",
    "Relationship promises missed. Show up for your relationships the way you want them to show up for you.",
    "No relationship checkins. Connection is built daily. Disconnection is also built daily.",
    "Relationship skipped. Your promises in this area define the depth of your most important bonds.",
    "No relationship today. The best version of your life has strong, intentional relationships at its center.",
    "Relationship missed. The people you love deserve the intentional, consistent version of you.",
  ],
  Career: [
    "Career promises missed. The skills you don't build today, someone else is.",
    "No career work today. The gap between you and your goal stayed the same.",
    "Career checkins skipped. Your professional growth doesn't pause when you do.",
    "No career today. The market doesn't care about your intentions, only your output.",
    "Career promises missed. The skills and habits you build now determine your ceiling.",
    "No career work today. Compound growth in your profession requires daily investment.",
    "Career missed. Someone else did the work you didn't today.",
    "No career checkins. The career you want is built in the ordinary days you show up for.",
    "Career promises skipped. The gap between you and the next level is made of these missed days.",
    "No career work today. Professional excellence requires the same daily discipline as any other promise.",
    "Career missed. The skills you're not building are the ones that will hold you back.",
    "No career today. Your professional reputation is built or eroded one day at a time.",
    "Career promises missed. The discipline to grow professionally every day is what separates the best from the rest.",
    "No career checkins. The work you do on yourself professionally compounds faster than almost anything else.",
    "Career skipped. Every day you invest in your skills is a day your future options expand.",
    "No career work today. The career of your dreams is built by the promises you keep today.",
    "Career promises missed. What you know today determines what you're worth tomorrow.",
    "No career today. The skills and habits you build now are the foundation of everything that comes next.",
    "Career missed. Professional growth is not automatic, it requires daily intention.",
    "No career checkins. The version of you that achieves your professional goals invested every day.",
    "Career promises skipped. The best in any field are the ones who showed up when others didn't.",
    "No career work today. Your professional trajectory is shaped by the promises you keep.",
    "Career missed. The investment in your professional skills today is the income of your future.",
    "No career today. Don't build the career you settle for, build the one you want.",
    "Career promises missed. Your craft requires daily practice, not occasional effort.",
    "No career checkins. Professional excellence is built the same way physical excellence is: daily.",
    "Career skipped. The work you're putting off is the work that's holding you back.",
    "No career work today. The difference between where you are and where you want to be is in these promises.",
    "Career missed. The skills you build today are the opportunities you get tomorrow.",
    "No career today. What you invest in your professional growth, the market returns to you.",
    "Career promises missed. Daily professional investment is the only reliable path to long term success.",
    "No career checkins. The gap between your current position and your goal is filled with days like today.",
    "Career skipped. Someone more disciplined than you did the career work today. Catch up tomorrow.",
    "No career work today. Professional promises exist because achievement requires daily commitment.",
    "Career missed. Your career is a long game but it's played one day at a time.",
    "No career today. Every missed career promise is a deferred investment in yourself.",
    "Career promises skipped. Build the skills now so you have the options later.",
    "No career checkins. The most valuable thing you can build is professional competence, build it daily.",
    "Career missed. The daily discipline of professional growth is what makes careers great.",
    "No career work today. Don't let your career happen to you, make it happen.",
    "Career promises missed. Your professional promises are the non-negotiable habits of high achievers.",
    "No career today. What you build today professionally becomes the platform for tomorrow's opportunities.",
    "Career skipped. The person who gets the opportunity you want did their career work today.",
    "No career checkins. Professional growth doesn't happen in big leaps, it happens in consistent daily steps.",
    "Career missed. Your skills don't stagnate, they either grow or decay. Don't let them decay.",
    "No career work today. The promises you made in your career category are there to close the gap between good and great.",
    "Career promises skipped. Every day you invest in your craft, you become harder to replace.",
    "No career today. The career you want is waiting on the other side of these daily promises.",
    "Career missed. Build now, harvest later. That's how career investment works.",
    "No career checkins. The best career investment you can make is the one you make every single day.",
  ],
  Money: [
    "Money promises skipped. Financial freedom requires daily decisions.",
    "Wealth is built in the boring moments you keep showing up for.",
    "No money checkins today. The financial gap between where you are and where you want to be is made of moments like this.",
    "Money promises missed. Every skipped financial promise is a deferred step toward freedom.",
    "No money work today. The financially free version of you made different choices.",
    "Money checkins skipped. Financial discipline is built one small decision at a time.",
    "No money today. The compound interest on good financial habits is extraordinary, start building it.",
    "Money promises missed. Wealth is not an event. It's a daily practice.",
    "No money checkins. The financial habits you build now determine your options later.",
    "Money skipped. Financial freedom is the result of daily financial discipline.",
    "No money work today. The version of you with financial security did the work on days like this.",
    "Money promises missed. Every good financial decision you make today pays dividends for years.",
    "No money today. Financial goals are long games. Play the daily moves.",
    "Money checkins skipped. The gap between where you are financially and where you want to be is filled with these daily promises.",
    "No money promises today. Wealth is built in the space between wanting and doing.",
    "Money missed. The financial habits you create now are the financial freedom you'll have later.",
    "No money work today. Financial discipline requires the same daily commitment as any other promise.",
    "Money promises skipped. The financially successful version of you has excellent daily habits.",
    "No money checkins. Every day you keep your financial promises is a day you invest in your future.",
    "Money missed. Small financial decisions compound into large financial outcomes.",
    "No money today. Financial independence is the result of making good financial decisions every day.",
    "Money promises missed. The wealth you want is built in the daily practices you keep.",
    "No money work today. Financial goals without financial habits are just wishes.",
    "Money checkins skipped. The financially free version of you has non-negotiable daily money promises.",
    "No money today. The cost of skipping your financial promises is paid in future options lost.",
    "Money missed. Every dollar you manage well today is a step toward the financial life you want.",
    "No money promises today. Financial freedom is built one disciplined day at a time.",
    "Money promises skipped. The gap between financial stress and financial freedom is filled with daily habits.",
    "No money checkins. The daily financial decisions you make determine the financial life you live.",
    "Money skipped. Wealth is the reward for sustained financial discipline. Build it daily.",
    "No money work today. Financial progress is slow, steady, and completely within your control.",
    "Money promises missed. The financial habits of the wealthy are available to everyone, few use them.",
    "No money today. The investment in your financial discipline today pays off in ways you can't yet see.",
    "Money checkins skipped. Financial security doesn't happen to you, you build it every day.",
    "No money promises today. The financially successful version of you didn't skip these.",
    "Money missed. Every skipped financial promise is a vote for staying exactly where you are.",
    "No money work today. The discipline of financial promises is what separates those who achieve freedom and those who wish for it.",
    "Money promises skipped. Small consistent actions compound into extraordinary financial results.",
    "No money checkins. Your financial future is built in the daily choices that seem small but aren't.",
    "Money missed. The cost of financial procrastination is paid in years, not dollars.",
    "No money today. Financial discipline today is financial freedom tomorrow.",
    "Money promises missed. Build the habits now. The financial rewards follow.",
    "No money checkins. The path to financial freedom is made of daily financial promises.",
    "Money skipped. Every day you practice financial discipline is a day your future self becomes more secure.",
    "No money work today. Wealth doesn't come from what you earn, it comes from what you practice daily.",
    "Money promises missed. The financial version of you that you want to be has these promises as non-negotiable.",
    "No money today. The compound effect of financial discipline over time is the most powerful force in personal finance.",
    "Money checkins skipped. Build financial habits today that will serve you for decades.",
    "No money promises today. Financial freedom is earned, not given, earn it daily.",
    "Money missed. The best financial decision you can make today is to keep your financial promises.",
  ],
}

const MISSED_GENERIC: ((cat: string) => string)[] = [
  cat => `You haven't touched your ${cat} promises today. That area doesn't maintain itself.`,
  cat => `${cat} got skipped. Every day you ignore it makes the comeback harder.`,
  cat => `Your ${cat} promises are still waiting. They don't expire but momentum does.`,
  cat => `Nothing done on ${cat} today. Small consistent effort beats occasional bursts every time.`,
  cat => `${cat} skipped. The version of you that takes this seriously would go back and fix it.`,
  cat => `You set ${cat} promises for a reason. Today that reason still applies.`,
  cat => `${cat} is sitting at zero today. One promise done is better than none.`,
  cat => `Your future self is going to want you to have taken ${cat} seriously today.`,
  cat => `${cat} undone. You already know what happens when you keep postponing this.`,
  cat => `Skipping ${cat} today is fine once. It becomes a pattern faster than you think.`,
  cat => `${cat} needs attention today. You put it there because it matters to you.`,
  cat => `No progress on ${cat}. The gap between who you are and who you want to be lives here.`,
  cat => `Your ${cat} promises are not suggestions. You wrote them because they move the needle.`,
  cat => `${cat} missed again. Notice that and decide if you are okay with it.`,
  cat => `You said ${cat} mattered enough to track. Act like it.`,
  cat => `${cat} sitting empty today. One action changes the day's story.`,
  cat => `Nothing checked in ${cat}. The effort required is smaller than the regret of skipping.`,
  cat => `${cat} got zero attention today. It will not improve on its own.`,
  cat => `Your ${cat} area is asking for something from you today.`,
  cat => `${cat} promises exist because past you knew present you would need the reminder.`,
]

// ── Engine ───────────────────────────────────────────────────────────────────

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)]
}

function keyForOffset(offset: number): string {
  const d = new Date()
  d.setDate(d.getDate() - offset)
  return d.toISOString().split('T')[0]
}

export function buildContext(checkins: CheckinsData, standards: StandardsData): MotivationContext {
  const today = keyForOffset(0)
  const todayData = checkins[today] ?? {}

  const score = scoreTodayLive(todayData, standards, today)
  const todayPct = score / 10

  // Active promises for today (respects createdAt - same filter as scoreDay)
  const activeCats = standards.categories
    .map(cat => ({ ...cat, standards: cat.standards.filter(s => !s.createdAt || s.createdAt <= today) }))
    .filter(cat => cat.standards.length > 0)

  // Missed categories - any active promise not checked
  const missedCategories = activeCats
    .filter(cat => cat.standards.some(s => !todayData[s.id]))
    .map(c => c.label)

  // 7-day rolling average (uses scoreDay internally - respects createdAt + equal weighting)
  const rolling7 = rollingAvg(checkins, standards, 7)

  // Trend vs yesterday
  const yScore = scoreDay(keyForOffset(1), checkins, standards)
  const trend: MotivationContext['trend'] = yScore === null ? 'new'
    : score > yScore + 0.5 ? 'up'
    : score < yScore - 0.5 ? 'down'
    : 'flat'

  // Top streak (per-promise streak, unaffected by weighting)
  const allIds = standards.categories.flatMap(c => c.standards.map(s => s.id))
  let topStreak = 0
  for (const id of allIds) {
    let streak = 0
    for (let i = 0; i < 30; i++) {
      if (checkins[keyForOffset(i)]?.[id]) streak++
      else break
    }
    if (streak > topStreak) topStreak = streak
  }

  // Perfect days this week - score must equal 10 (all active promises done)
  let perfectDaysThisWeek = 0
  for (let i = 0; i < 7; i++) {
    if (scoreDay(keyForOffset(i), checkins, standards) === 10) perfectDaysThisWeek++
  }

  return {
    score, trend, todayPct, missedCategories,
    topStreak, dayOfWeek: new Date().getDay(),
    perfectDaysThisWeek, rolling7,
  }
}

export function getMotivation(ctx: MotivationContext): string {
  const { score, trend, todayPct, missedCategories, topStreak, dayOfWeek } = ctx

  // Perfect day
  if (todayPct === 1) return pick(PERFECT)

  // Zero day
  if (todayPct === 0) return pick(ZERO)

  // Streak shoutout (>= 5 days, 30% chance)
  if (topStreak >= 5 && Math.random() < 0.3) {
    const fn = pick(STREAK)
    return fn(topStreak)
  }

  // Missed specific category (40% chance)
  if (missedCategories.length > 0 && Math.random() < 0.4) {
    const cat = pick(missedCategories)
    if (MISSED_CATEGORIES[cat]) return pick(MISSED_CATEGORIES[cat])
    return pick(MISSED_GENERIC)(cat)
  }

  // Day-of-week context (25% chance)
  if (Math.random() < 0.25) {
    if (dayOfWeek === 1) return pick(MONDAY)
    if (dayOfWeek === 5) return pick(FRIDAY)
    if (dayOfWeek === 0 || dayOfWeek === 6) return pick(WEEKEND)
  }

  // Trend (30% chance)
  if (trend === 'up' && Math.random() < 0.3) return pick(IMPROVING)
  if (trend === 'down' && Math.random() < 0.3) return pick(DECLINING)

  // Score-based fallback
  if (score <= 2.4) return pick(ARE_YOU_KIDDING)
  if (score <= 4.9) return pick(POOR)
  if (score <= 7.4) return pick(BAD)
  return pick(GOOD)
}
